### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#10]
Here are [content ideas](http://wiki.code4lib.org/Conference_Site_Pages#About)!

**Comment by billmcmillin** [comment]
I can take this one.

**Comment by sdellis** [comment]
:+1: Go for it!

**Comment by cdmo** [comment]
someone should probably add @billmcmillin to the code4lib group so that this issue can be assigned to him?

**Comment by sdellis** [comment]
He's been invited.  I will assign this to him when he joins.

**Comment by billmcmillin** [comment]
Page added and merged. I'll update it again when we have more specifics on venue and contact info.
