### ISSUE TITLE
Add proposal form links to 'speakers' page

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#124]
Reasoning is that people may click 'speakers' to find out how to become one.

Downside is that these would then be in two places (currently on 'schedule' page).

**Comment by sdellis** [comment]
@hackmastera ... I agree that the navigation is currently focused toward an "attendee" audience.  We could have the proposal submission in both places, or move it to Speakers.  Another possibility is to have an "Announcements" section on the home page, where the 1-3 most pressing announcements would go?  Any other ideas?

@roastduckalamode

**Comment by queryluke** [comment]
@hackmastera @sdellis Personally, I like the announcements section, which would also be useful during the conference for any updates or notifications. If we make it now, users may get used to looking there for relevant info.

In addition to having an announcements section, we could create a single page with all of the pre-conference information. Then on the schedule and speaker pages just have a link to the new page that says "Interested in being a speaker, learn how?" and "Interested in giving a talk, learn how?".

**Comment by hackartisan** [comment]
@sdellis thanks for adding the link! I like the idea of an announcements section, as well, although I worry that it would be far down enough on the front page to be overlooked? Anyway I am satisfied now :) Any further information re-architecture would probably worthwhile but not necessary! @roastduckalamode

**Comment by queryluke** [comment]
@hackmastera I've got an idea for an announcements section, but I need to find the time to code it. I'm thinking of a simple css animation under the conference dates (upper-right) that rotates announcements. I think I'll have some time this weekend to experiment.
@sdellis
