### ISSUE TITLE
Try using the post-commit hook

### ISSUE THREAD

**Issue by starsplatter** [code4lib/2016.code4lib.org#14]
See: http://oli.jp/2011/github-pages-workflow/

**Comment by sdellis** [comment]
It should be as simple as adding a `.git/hooks/post-commit` file with this in it:

```
#!/bin/sh
git checkout gh-pages
git rebase master
git checkout master
```

@roastduckalamode do you have a Jekyll branch you can do a pull-request on so we can merge and try it out?

**Comment by starsplatter** [comment]
tossing this back to @sdellis since he knows what's up and I'm getting bogged down!

**Comment by queryluke** [comment]
@sdellis Yes, I've created a pull request for issue#3. This one is jekyll ready

**Comment by queryluke** [comment]
Doesn't look like the post-commit hook worked. Master was updated but gh-pages was not.

**Comment by queryluke** [comment]
going to close this as using the gui is working just fine
