### ISSUE TITLE
Remove workshop proposal submission links on Nov 15

### ISSUE THREAD

**Issue by queryluke** [code4lib/2016.code4lib.org#146]
I've preloaded a branch for this

**Comment by dlacy** [comment]
Could you do the same for the Talk Proposal form link?

**Comment by sdellis** [comment]
@roastduckalamode hey, can you update this?  I did make some changes to the Schedule page, but they can be overwritten by your branch.  Changes to other files should not be overwritten.  Thanks!

**Comment by hackartisan** [comment]
y'all are tops.
