### ISSUE TITLE
pre-conference content strategy?

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#159]
I'd like to hear more info about the vision for the 'schedule' page.

currently the two pre-conference-specific pages are http://2016.code4lib.org/propose-a-workshop.html and http://2016.code4lib.org/proposed-workshops.html neither of which is an appropriate url for finalized workshop info.

I guess we'll want a new page with the final workshops where we can post:
- schedule
- locations (both street maps and internal building maps since there will be multiple sites)
- workshop summaries
- links to resources for pre-downloading and pre-installing

Let me know if there was some other plan already in place to accommodate this content! If not maybe someone could create a stub and we could start pre-populating to the extent possible?

**Comment by sdellis** [comment]
We haven't talked about this extensively, but I was thinking the schedule page would change after voting is completed.  It would only be a schedule, similar to the [eduiconf schedule](http://eduiconf.org/schedule/).  However, I could see sessions color coded or have some icon, so that you knew what building/room they were in.  Clicking through would take you to a session/talk detail page which would have any necessary prep-information. 

Certainly makes sense to reconvene the Web Committee and start prepping for this, so thanks for the heads-up @hackmastera. We also really need a Scholarships page!

**Comment by queryluke** [comment]
Since I stubbed the schedule page, here is what I had planned:

When we have all the info, the schedule menu-nav with turn into a dropdown with Preconference, Day1, Day2, Day3 as choices.

Day 1-3 will use the timeline display that we're using for past keynotes, with an analog clockface in the blue dot on the left (but also the digital time in the panel), and click-through to the full abstract, speaker info, slides, etc.

For preconference, I was going to put some simple navigation buttons at the top of the page that would filter the workshops by time (am/pm/all day) and location. Also, click-through with more details (slides, links to resources), and selecting a location will provide a map link. However, if it's not working out, we have the table-style display as a backup.

I don't think I can have anything stubbed this week...would Nov 30th be too late? If voting ends on the 2nd, we can gather feedback and export the data that week as well. Then the page would be live by Dec 7th. Is that an acceptable timeline?

@hackmastera How many locations will we have?

**Comment by sdellis** [comment]
@roastduckalamode Yes, now I remember!  Very cool.  Dec 7th would be fine as registration is slotted to open Dec. 10th... and even if it's a little later, it's not the end of the world.  I think we're working out locations this and next week, but @hackmastera may have some rough notion of how many we would _like_.

**Comment by queryluke** [comment]
@sdellis @hackmastera 
I've stubbed a sample of how final workshops will look. Pull issue-159 to your local repo to view. I've used [fromSheetsToJekyll](http://roastduckalamode.github.io/fromSheetsToJekyll/) to do most of the heavy lifting in terms of "data entry". Here is the [documentation](https://docs.google.com/document/d/1LvQ4KWqNaj4NjScFAsdQsQ_OtgRWric7M8dAq6RIXdo/edit?usp=sharing).

Once locations are set and voting closes, we can work towards a finalized Sheet that contains all of the relevant information (length or workshop, locations, resource links).

**Comment by hackartisan** [comment]
@roastduckalamode I haven't had a chance to look at this yet but hope to soon. I wanted to ask, though, whether email addresses will be published or kept confidential? If they'll be published we'll have to make them optional to provide.

**Comment by queryluke** [comment]
@hackmastera  We can leave them private. But if we're using them as a key, they would be accessible in the repo's data files.

**Comment by hackartisan** [comment]
Hm. :( I'm not crazy about that. But I can't think of another way of matching presentations / presenters.

**Comment by sdellis** [comment]
Looks good to me, @roastduckalamode.  How about twitter handle as the key?  Most speakers post those anyway for questions.

**Comment by phette23** [comment]
It seems a bit iffy to assume all presenters will have a Twitter handle, much as I like that idea.

**Comment by sdellis** [comment]
What better time to create one! Seriously, let's not overthink this. If
you're going to be speaking there needs to be a way for people to contact
you to ask follow up questions, or to sing your praise. Twitter seems like
the least common denominator to me, but open to other suggestions.

**Comment by queryluke** [comment]
@sdellis We don't have their twitter handle stored in the original, workshop proposal from. We need a value in that form to associate with the speaker form.

If people are that sensitive about their emails, I can see 2 other options:
1. manually entering an ID in the speaker form and workshop proposal form once all speaker info has been collected.
2. trying to use name and manually checking / editing any mismatches

We may have to do option 2 using email as the key anyway. So (as I'm thinking through this as I type) maybe we can ask for email and name. Try to use name. If there are a lot of mis-matches with the name, I can try and write a script that matches via email, then converts the key to a standard name or id. No guarantees. But we'll at least have the email as a back-up key to make the initial association.

**Comment by sdellis** [comment]
Gotcha.  For the record, I am not sensitive about emails and I don't see a
problem with it.  And remember, we are talking about a non-displayed
field.  There is a long history of people posting them all over the wiki as
a means of contact.

**Comment by hackartisan** [comment]
I think a lot of people are sensitive about emails. Often people post them on the wiki in an obfuscated style (i.e. symbols become words). That's not very useful in use as a key.

I think if we're going to collect emails with the intent to publish them (either incidentally in the github repo or directly on the site) then people should be allowed to opt out.

@roastduckalamode thank you for your flexibility in being willing to work around this issue.

We need to be ready to send out a link to this form tomorrow afternoon. We will have to ask for emails so we can use them to contact people. So let me know whether you want us to include a "do not publish my email address" button or just a note that it won't be published.

Thanks!

**Comment by hackartisan** [comment]
@roastduckalamode i looked at branch issue-159 and it looks great.

We will plan to provide locations in the format your documentation indicates. We have time to coordinate all these pieces; the main thing we are in a hurry on is how we collect presenter data, since as I already noted we're about to send out that form.

**Comment by queryluke** [comment]
@hackmastera Either way works. I see more flexibility in providing the opt-out option. If no one opts out, we're set. If people opt-out, we'll find a work around. Additionally, if we allow people to opt-out we can publish the emails of those who opt-in on the speakers pages. 

But if you think it safer to simple say "we won't publish your email", then I'm fine with that as well.

**Comment by sdellis** [comment]
I pulled issue-159, but I don't know where the workshop mockup is. I would
have thought it would be in the schedule section.

Do we want to collect twitter handles as well?  This way, if they opt out
of email, we have a unique key for them that we can map to their email
address in the other table? I think most people would prefer twitter
handles on the speakers pages to email.

**Comment by queryluke** [comment]
@sdellis the stub replaces workshops.html

@hackmastera said they were using my mock form from #75 , so I think they're plan to collect handles as well.

**Comment by sdellis** [comment]
This looks great, Luke. Thanks.  I fixed a margin/padding issue and made
the cards display in a flexbox layout.  There is a lot more we could do in
the way of UI improvements, but you've done so much already and it's a
matter of priorities or shared labor... speaking of which, where did the
rest of our web committee go? :-/

Anywho, kudos! Let's run with it! :)

**Comment by hackartisan** [comment]
@roastduckalamode will this change the urls that look like: http://2016.code4lib.org/workshops#Publishing-Research-Data-with-R-Knitr-and-Shiny
?

Because I'm about to add them all into the registration form.

**Comment by queryluke** [comment]
The urls would change to http://2016.code4lib.org/workshops/[workshoptitle]. This is the full preconference "post". Which will contain the abstract, speaker name, location, time o day, etc.

The title should be the same because I used the same regex script to parse out non-alphanum chars. So, tl;dr,  switch the `#` to a `/`

**Comment by hackartisan** [comment]
@roastduckalamode then I think we should either deploy the individual pages this weekend or leave the current page in place until registration closes. let me know which you prefer! Thanks.

**Comment by queryluke** [comment]
@hackmastera If we deploy this weekend, I can make the location TBD. And I'll figure something out for the speaker data, since we don't have the official information yet.

But I need the finalized list of selected preconference workshops with their lengths (am, pm, full day). Has that all been figured out?

**Comment by hackartisan** [comment]
@roastduckalamode Hm, we are waiting for confirmations. The confirmation deadline is Monday.

Maybe we could deploy on Tuesday? Registration will open on Thursday so that would give us a minute to test the links and tweak any problems.

**Comment by queryluke** [comment]
@hackmastera works for me. Once we have a finalized spreadsheet it will only take about 5 minutes to compile and upload the files.

**Comment by hackartisan** [comment]
@roastduckalamode Remind me which spreadsheet you've been using for your work so far? We have a number of them :)

**Comment by queryluke** [comment]
@hackmastera For [issue-159](https://github.com/code4lib/2016.code4lib.org/tree/issue-159) I used a copy of the preconference proposal responses sheet. I think the title of the sheet is _Code4Lib 2016  (Responses)_. Here is [my copy](https://docs.google.com/spreadsheets/d/1W87SnH9R8rCADygAKwVGTE5fvoWLac0IEAn8l40p34s/edit?usp=sharing), which has length and fake location added.  

But fromSheetsToJekyll should be able to handle any Google Sheet. If you have an up to date sheet you've been using to administer the preconference scheduling, voting, etc we can use that one instead. 

For publishing individual pages, all I'll need is a column that has the length-of-day. The column name can be anything. I wrote the jekyll files to parse the values "am", "pm", and "full", but honestly those values can be anything as well. Just need to know what they are so I can code it in the site.

**Comment by hackartisan** [comment]
note we'll probably want 2 location fields: building and room.

**Comment by queryluke** [comment]
Yep. Anna has been in touch. Displaying the building and room is no prob. But do we need to filter by room on the workshops page? Or will building be sufficient?

**Comment by queryluke** [comment]
I've published the workshops. For documentation's sake here is the list of workshop urls:

http://2016.code4lib.org/workshops/lodashjs-API-tour
http://2016.code4lib.org/workshops/User-Experience-for-Libraries--Collections
http://2016.code4lib.org/workshops/The-Getting-Ready-for-Workshops-Workshop
http://2016.code4lib.org/workshops/Semantic-Search-for-The-CoderLibrarian
http://2016.code4lib.org/workshops/RailsBridge-Intro-to-programming-in-Ruby-on-Rails
http://2016.code4lib.org/workshops/Publishing-Research-Data-with-R-Knitr-and-Shiny
http://2016.code4lib.org/workshops/Migrating-Hydrabased-repositories-from-Fedora-3-to-4
http://2016.code4lib.org/workshops/Measuring-Your-Metadata
http://2016.code4lib.org/workshops/Linked-Data-Learning-Tips-Tricks-and-Lessons-Learned
http://2016.code4lib.org/workshops/Its-Always-Sassy-in-Philadelphia
http://2016.code4lib.org/workshops/Islandora-for-Managers
http://2016.code4lib.org/workshops/Islandora-for-Developers
http://2016.code4lib.org/workshops/HandsOn-Fedora-4
http://2016.code4lib.org/workshops/Getting-More-out-of-Your-Maps-Georeferencing-and-Optimizing-Digitized-Maps-for-Use-in-Web-Applications
http://2016.code4lib.org/workshops/Fail4Lib-2016-Failadelphia
http://2016.code4lib.org/workshops/Dive-deeper-into-Hydra
http://2016.code4lib.org/workshops/Dive-Into-Hydra
http://2016.code4lib.org/workshops/Digitization-Project-Starter-What-you-need-to-know-to-plan-that-OCR-project
http://2016.code4lib.org/workshops/Customizing-Blacklight-Approaches-and-Best-Practices-
http://2016.code4lib.org/workshops/Command-Line-Bootcamp
http://2016.code4lib.org/workshops/Code4Arc
http://2016.code4lib.org/workshops/Catmandu--a-metadata-toolkit
http://2016.code4lib.org/workshops/Buzzword-compliant-Logging
http://2016.code4lib.org/workshops/Building-a-Geocoding-Toolset-for-Libraries
