### ISSUE TITLE
Link directly to individual workshop descriptions?

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#162]
Is there any easy way to add in anchors so that we can link directly to a single, expanded workshop description? The voting form doesn't allow us to make these expandable so we'd like to provide direct links instead to reduce visual clutter.

Currently our only option may be to copy everything back over to the wiki so we can link to the descriptions :(

**Comment by hackartisan** [comment]
(just as background: we're using a google form for voting because the usual code4lib voting app doesn't work well for workshop selection (when a person will only attend a single workshop in each time slot)

**Comment by queryluke** [comment]
@hackmastera can I see what the form looks like? 

We can create static pages for each of the workshop proposals and you can link to the page. The problem is defining an ID. I've been removing special characters from the proposal timestamp, but if you're hard coding the links into the form, we'd have to figure out something else.

**Comment by hackartisan** [comment]
The set is finite at this point; can we just use a variation of each title?

**Comment by hackartisan** [comment]
Oh, the form is totally not finished yet. But we will basically publish it as soon as it is ready (i.e. some time today) so if there's no quick way to grab an anchor into the existing page, maybe it's not worth doing.

**Comment by queryluke** [comment]
In the interest of time, I made a second page with anchor links. The anchor links use the full title with all special characters removed and spaces replaces by dashes. Here is the regex used if you're using Apps Script to create the form

`id = entry["Preconference Title"].replace(/[^\w\s\d]/gi, '');
    id = id.replace(/[\s]/gi, '-');`

the page is http://2016.code4lib.org/workshops

Let me know if that doesn't work for your needs

**Comment by hackartisan** [comment]
@roastduckalamode You are a hero!!

**Comment by hackartisan** [comment]
Wait I think maybe the anchor needs to be inside the div? the page is loading such that the heading is off-screen for me.

**Comment by queryluke** [comment]
My bad! I was using the cssID twice. I'm pushing now, may take a few minutes for the site to re-compile

**Comment by hackartisan** [comment]
Works great. Thank you!!
