### ISSUE TITLE
Change childcare info to indicate there will be a form separate from registration form

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#182]
This TODO taken from LPC email thread 'followups from yesterday' Nov 30.

**Comment by billmcmillin** [comment]
I can take this one. I'm not on the LPC list. Is there anything we need to say other than "there will be a form separate from the registration form"? Any additional info on when/where the form will be available?

**Comment by bibliotechy** [comment]
@billmcmillin Sorry for the delay in responding. I don't yet have the details available, but I will get them tomorrow. For now, just indicate that there will be a separate form and details TBD. Thanks
