### ISSUE TITLE
Embed t-shirt voting form in 2016 Conference website?

### ISSUE THREAD

**Issue by cmharlow** [code4lib/2016.code4lib.org#185]
Hey all-

Do you want to embed the 2016 Tshirt voting form (built with form+, an extension of Google Forms that allows users to upload files) into the Code4Lib site? Otherwise we will send out the direct link to the form+ form. See a sample form here: http://goo.gl/Rk6rtG

The form results go into a Google sheet, which I will share with the appropriate folks if you want to display received submissions so far on the site as well.

If this could be decided yay/nay before Monday Dec. 7, noon Eastern, that'd be extra rad.

Thanks,
Christina

**Comment by bibliotechy** [comment]
Personally don't care either way about embedding the form into the website. We'v been linking to all the others which seems fine enough. 

Submissions appearing on the website sounds like a great idea. Share and we'll get to it.

**Comment by cmharlow** [comment]
Thanks @bibliotechy - will use a bit.ly to the form+ form for the email call (which will go out Monday AM).

I'll share the submissions responses folder (including spreadsheet and folder with images) to you web folks. Its currently in the Code4Lib Tshirts Google Folder, which you guys may already have access to.

Thanks,
christina

**Comment by bibliotechy** [comment]
:+1:
