### ISSUE TITLE
Publish the Voting results for Talk Proposals

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#196]
Use SheetsToJekyll to list voting results, similar to the [workshops page](http://2016.code4lib.org/workshops/).

**Comment by sdellis** [comment]
@roastduckalamode I'm trying to create a YAML file from a Sheetsu API that I made (https://sheetsu.com/apis/922efaf4).  It doesn't seem to be working.  Is [this site](http://roastduckalamode.github.io/fromSheetsToJekyll/) still legit or is there somewhere else I should go to do this?

**Comment by queryluke** [comment]
@sdellis I scrubbed Sheetsu for tabletop.js. So you'll need to publish the sheet to the web and use the public url instead. At some point in the future, I plan to make fromSheetstoJekyll work with sheetsu as well

I should probably change the label of the first input...whoops!

**Comment by queryluke** [comment]
@sdellis also, If you want an individual page for each talk (similar to the workshops pages), you'd use the templates method. It will create zip of html files that you can c/p into the _posts directory. 

But if this is just information about the voting (i.e. you're just making a list of titles and vote counts without additional information like time, slides, etc), then the data file will suffice.

Let me know if I can help.

**Comment by sdellis** [comment]
I have set the settings to "anyone with a link" can view and paste the url into the field, but the "Check" button is still not working. Does it need to be completely Public?

**Comment by sdellis** [comment]
@roastduckalamode Could certainly use your help here since we are planning on sending out a reminder at some point today with links to the Workshops and Talk results.

**Comment by queryluke** [comment]
@sdellis yeah, you have to actually publish the sheet to the web. Then use the public url. But you can unpublish right after. Or send me the sheet link and I can help out.

**Comment by queryluke** [comment]
@sdellis also, here is the [sheetsu flavored version](http://roastduckalamode.github.io/fromSheetsToJekyll/sheetsu.html)

**Comment by sdellis** [comment]
Ok, there are access control headers that are preventing the sheetsu
version from working and I am getting a bunch of javascript errors in the
other one.... I emailed you the link to the spreadsheet.

**Comment by queryluke** [comment]
I've imported into [issue-196](https://github.com/code4lib/2016.code4lib.org/tree/issue-196)

This isn't how I have planned to do the final presentation of talks. We'll need the speaker data, time and dates for that. But this works in the interim. Like the workshops (in /workshops) the list is found at /schedules

Not sure how you want to handle the architecture. My thoughts
- Remove schedule.html and replace any links to this page as /schedule
  OR
- change the directory name from /schedule to /talks and put that link wherever

**Comment by sdellis** [comment]
Sorry for this lacking context, @roastduckalamode .  The final selection has not been made for Talks. Since we are going live with registration tomorrow, and we would like to give folks (especially noobies) an  idea of the content, we want to list the election results.  This is not the way the final talks will be presented, but we need to list them in order of vote count so that people have an idea of what to expect before they register. 

That said, I would not change schedule.html, just provide a link to the Presentations voting results page.

**Comment by queryluke** [comment]
@sdellis will do. Do you want me to show the vote count? And/or order the proposals by vote count?

**Comment by sdellis** [comment]
Yes, and yes. You could make the vote count fairly large on the card/div and perhaps even highlight the top 10 since those are definitely accepted.  I will add the text at the top of the screen explaining that this is not the final selection list, but will give folks a sense of the content of the talks.

**Comment by queryluke** [comment]
@sdellis done and sort of done. The top 10 have a class .top-10, but I wasn't sure how best to highlight these. All you should need to do is play around with the css. I tried a blue highlight at first but the red link text seemed a bit wonky. 

the link is /talks

I've also updated the schedule page. The Vote buttons now say "View Results" and link to /talks and /workshops respectively.
