### ISSUE TITLE
Speaker information form

### ISSUE THREAD

**Issue by queryluke** [code4lib/2016.code4lib.org#199]
@hackmastera and I discussed the process of gathering information about speakers. She suggested that the website working group create the form and disseminate it to the Pre-conference and Program committees to ensure that the form be unified across both. I'm happy to spin up a form, but need to know what data we want to collect about the speakers.

In our stub, we have
- name
- affiliation
- email
- twitter handle
- image
- bio

RE: emails
- I'll make a note that the emails will not be published, but are being used to associated the speaker to the talk.

RE: images
- Do we want to require that the image be hosted elsewhere (i.e. they'll provide a url)?
- or I can provide my email address and have people send me a file (like we're doing with logos)

**Comment by queryluke** [comment]
@sdellis Are presentation selections final? I can whip up a form and send it to the necessary committees so we can start building out the final speaker / schedule pages.

**Comment by sdellis** [comment]
@roastduckalamode they became final this morning and I asked the Program Committee folks to ask for an image and bio for speakers.  I forgot about these other data points. I'm forwarding them this issue so they can include them.

**Comment by queryluke** [comment]
@sdellis Will the programming committee be gathering the data for the preconference workshops as well? If not, will you ask them to share their form with the preconference committee.

**Comment by bibliotechy** [comment]
@roastduckalamode @sdellis  do you want info from the keynotes in the same format, or do we have a different idea for that?

**Comment by queryluke** [comment]
@bibliotechy The info seems fine. I've sent a form to the program and workshop committee. Do you need me to send you one for keynotes?

**Comment by bibliotechy** [comment]
Sure, whatever is going to be easiest for you to deal with.

**Comment by queryluke** [comment]
@bibliotechy just sent you the form.

**Comment by bibliotechy** [comment]
@roastduckalamode thanks. I'm just going to fill them in myself since I've requested the data from the speakers directly.
