### ISSUE TITLE
Workshop listings look odd on Firefox on Linux

### ISSUE THREAD

**Issue by bibliotechy** [code4lib/2016.code4lib.org#202]
On Firefox 42 on Ubuntu Desktop, the workshop layout looks like this. 
![wideworkshop](https://cloud.githubusercontent.com/assets/1128631/11689370/9accb094-9e5f-11e5-999e-2487a31fad89.png)

I'm poking around, but if you have any ideas @roastduckalamode please point me at them.

**Comment by queryluke** [comment]
Happening on my Firefox as well. Looks like the culprit is display:flex in the .sequence class. @sdellis, did you make the change to flex instead of bootstraps built in grids? Another option is loose the 3 column layout altogether and have 1 workshop per row. Just makes for a longer page.

**Comment by queryluke** [comment]
@sdellis @bibliotechy nvm. I got it. Making the changes now.

**Comment by bibliotechy** [comment]
@roastduckalamode++
