### ISSUE TITLE
Contributor Level Sponsor Logos Illegible

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#225]
See UNC and UT Austin in particular...
http://2016.code4lib.org/sponsors.html

This uses a Bootstrap responsive layout.  Perhaps a Flexbox approach (like we use on the workshops page) would give us more control? Should we boost logos across the board?

Can someone from the website committee take a look and try to resolve? @roastduckalamode @cdmo @starsplatter @phette23 We're up to our eyeballs on the Planning committee as we make final programming and event arrangements.  Many thanks!

**Comment by cdmo** [comment]
As someone who had to create a logo page in the past, I know these are a pain to get right.  

Seems like there's a hierarchy in terms of size of logo in proportion to the size of donation. So, for the entities that give less but have complicated logos, I think that it's just going to be the best you can do without getting another logo or making the logos bigger and bucking the size restraints.. The logos are linked though, so at least there's that.

So I guess I'm saying I think they're okay as is.

**Comment by queryluke** [comment]
I'm in a bit of a whirlwind myself, I started a new job on Monday, and I've got a site migration scheduled from my old job this Sunday, which I'll need to be monitoring the next few weeks. I'm still committed to working on the schedule pages once the line-up is set. If I do happen to be twiddling my thumbs, I'll take a look at this.

**Comment by sdellis** [comment]
Ha! Congrats @roastduckalamode ! You'll have to fill us in. @cdmo Yes, I tend to agree, but this is really all Contributor level gets for their $250-$999, so legibility would be nice.  I'm going to look into display:table (works in IE8/9) instead of the responsive grid.  Could always go old school and lay it out in a giant png and image map it!  hand_massaged_logos--

**Comment by sdellis** [comment]
Done.
