### ISSUE TITLE
{{ site.data.path }} and local development

### ISSUE THREAD

**Issue by cdmo** [code4lib/2016.code4lib.org#23]
This variable `{{ site.data.path }}` outputs `/2016.code4lib.org/`.  So

`<link rel="stylesheet" href="{{ site.data.path }}prototype/bootstrap/dist/css/bootstrap.css">`

produces:

`<link rel="stylesheet" href="/2016.code4lib.org/prototype/bootstrap/dist/css/bootstrap.css">`

Which, of course, doesn't load anything and the page just loads HTML.  All of the links in header and footer break locally too.

@roastduckalamode am I missing something?

**Comment by queryluke** [comment]
If you're working locally, you need to change _data/path.yml to "/", then it will put out

`href="/prototype/..."`

**Comment by cdmo** [comment]
Okie doke
