### ISSUE TITLE
Set up 2016 t-shirt logo vote

### ISSUE THREAD

**Issue by ghost** [code4lib/2016.code4lib.org#230]
Hi @cbeer,
Can you please set up voting for the 2016 t-shirt logo design? @cmh2166 created jpegs of the submissions, which I think @bibliotechy plans to display on the 2016 website for voting purposes. If possible, can the vote begin on January 20 and close on the 27? 
The four jpegs and a spreadsheet with info for the Die-bold-a-tron are in the Tshirt Committee's Google folder called "2016 Submissions." Some folks like @bibliotechy have access to this folder, but please let me know if you need it. Is there anything I'm forgetting?
Thanks,
Lauren

**Comment by cbeer** [comment]
Could you link me to the folder, and/or attach the images to this ticket?

**Comment by ghost** [comment]
Done!

**Comment by cbeer** [comment]
![banerjee_scott](https://cloud.githubusercontent.com/assets/111218/12365604/b425eb44-bb8a-11e5-8484-d7939f4fc377.jpg)
![ellis](https://cloud.githubusercontent.com/assets/111218/12365603/b424a90a-bb8a-11e5-9f5d-7febde6ae9f1.jpg)
![markman](https://cloud.githubusercontent.com/assets/111218/12365605/b42769b0-bb8a-11e5-92b5-657b57c7b495.jpg)
![zoechao](https://cloud.githubusercontent.com/assets/111218/12365606/b42adb4a-bb8a-11e5-9e78-addf1df92c6f.jpg)

**Comment by cbeer** [comment]
http://vote.code4lib.org/election/40
