### ISSUE TITLE
Change workshop locations

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#244]
Workshops have been shuffled to final locations and the site needs to reflect new locations.

ALSO: We have changed the names of two rooms in Franklin Hall. 'Side - East' it turns out is called 'Fels Room' and 'Side - West' is called 'Presidents Room'

@roastduckalamode the spreadsheet in use is called "Preconf room assignments - Main Working Document" I am nearly positive this is the one we were using before, but some columns have likely been shuffled. please let me know if you need me to adjust anything.

**Comment by queryluke** [comment]
@hackmastera done!

**Comment by sdellis** [comment]
@hackmastera do you have a floor plan?  That would certainly help people find their way around.

**Comment by sdellis** [comment]
(Even a "back of a napkin sketch" would probably help.)

**Comment by hackartisan** [comment]
@roastduckalamode sweet, thanks!!!

@sdellis "talk to website folks about maps" is close behind on my to-do list :) Will create a separate issue!

**Comment by hackartisan** [comment]
Oh, I think we can remove the "Please note: all locations are subject to change through the close of registration" -- barring the unforeseen, these are final locations.

**Comment by queryluke** [comment]
@hackmastera I'll rope that change into the schedule pages that we're publishing later today.

**Comment by hackartisan** [comment]
Sounds good; thanks!!

**Comment by cmharlow** [comment]
Sorry, is this still being worked on (so explaining that the Workshops Schedule page is blank)? http://2016.code4lib.org/workshops/

**Comment by bibliotechy** [comment]
We are currently experiencing technical difficulties with the github site. :(

**Comment by cmharlow** [comment]
Good to know, will alert those asking. Thanks.

**Comment by queryluke** [comment]
Well that happened. Workshops should be back up and running
