### ISSUE TITLE
Speaker2.html page incomplete

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#25]
@jtidal  I see where you are going with the speaker2.html page, but it's very rough around the edges... the title bar says "Start Bootstrap" to start.  If you are going for a "non-stripey" simple white page, you can use the existing template and jekyll includes.  I merged it, but please fix and resubmit.

**Comment by jtidal** [comment]
Oh sorry, that's a test file that should be removed.

I was testing the modals against the css file in the repo, which is causing the background and foreground to darken. The correct file to use is speakers.html.

> > > Shaun Ellis notifications@github.com 8/11/2015 2:56 PM >>>
> > > @jtidal  I see where you are going with the speaker2.html page, but it's very rough around the edges... the title bar says "Start Bootstrap" to start.  If you are going for a "non-stripey" simple white page, you can use the existing template and jekyll includes.  I merged it, but please fix and resubmit.

---

Reply to this email directly or view it on GitHub:
https://github.com/code4lib/2016.code4lib.org/issues/25

**Comment by sdellis** [comment]
Ok, well, it looks like speakers.html was deleted.  I'm going to revert this back.

**Comment by sdellis** [comment]
Also, make sure to use a .yml file for speaker data if you weren't already going there.  It will make things easier to export/import into the site.  Closing this out.
