### ISSUE TITLE
precon locations map

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#291]
I made this up; see if it works for the website?

https://www.google.com/maps/d/edit?mid=z6mAEboBiRlo.kUgjHJeiYJIk

**Comment by queryluke** [comment]
@hackmastera @sdellis @bibliotechy 

Thoughts on how to handle these? Some options:

We can link directly into google maps, but this wouldn't help with the floor plans.

We could make a workshop location page (all 3 locations on one page), with embedded maps and floor plans, using anchor links to jump between the 3 locations. Not indicating the different rooms.

We could make a page for each location (1 location per page with embedded map) and edit the floor plans you provided by highlighting the rooms. Then provide anchor links to the floor plan. But then the map would be at the top of the page (might get lost).

@hackmastera and thanks for putting together the google map, but unfortunately, I can't link to an individual location. It's all 3 or nothing (unless I'm overlooking something).

**Comment by hackartisan** [comment]
I can make individual ones if you like. I don't have a strong preference on how this is done actually. :/ whatever is easiest for y'all?

**Comment by queryluke** [comment]
@hackmastera I've made a new branch called workshop locations. Clicking a building name will open in google maps. Clicking a room will open a modal dialog with the floor plan and some brief instructions. Waiting to hear back about the Franklin rooms (left or right on presidents / fels room). then I can adjust that image and pull

**Comment by hackartisan** [comment]
Sounds great; thanks so much
