### ISSUE TITLE
precon - floor plans

### ISSUE THREAD

**Issue by hackartisan** [code4lib/2016.code4lib.org#292]
Here are some CHF floor plans

http://www.chemheritage.org/visit/conference-center-rental/floor-plans.aspx

It may be better to post 0 floor plans or floor plans for all 3 locations, rather than just these.

**Comment by hackartisan** [comment]
Here's a hotel floor plan that I grabbed out of the PDF on their site; maybe one of you can do a better job if needed.

preconferences will be in bromley-claypoole (2/3) and Cook (9)

![floorplans_166](https://cloud.githubusercontent.com/assets/845363/13083539/817a50d6-d4a3-11e5-8083-2ed2ace15fd7.png)

http://www.starwoodhotels.com/sheraton/property/meetings/stacked_map.html?propertyID=166&buildingKey=1013372586&floorKey=all

**Comment by hackartisan** [comment]
There's no floor plan for APS's Franklin Hall but it's very straightforward - one front door to a hallway with a room on either side and one straight ahead.

**Comment by queryluke** [comment]
@hackmastera do you know which room will be which? Pres, Fel, Large Hall (left, right, straight)?

**Comment by hackartisan** [comment]
Fels Room is on the East side (right); Presidents Room is on the West (left). Large hall is north (straight ahead).
