### ISSUE TITLE
Stub/Mock Schedule Pages

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#3]
Stub/Mock out Schedule pages with a TBA fallback page we can use until sched is announced.

Here are some [content ideas](http://wiki.code4lib.org/Conference_Site_Pages#Schedule).

**Comment by queryluke** [comment]
Yep, I'm taking this. Just assign it my way

**Comment by queryluke** [comment]
Thoughts on using a timeline! Two examples:
http://codyhouse.co/demo/vertical-timeline/index.html
https://technotarek.com/timeliner/timeliner.html

**Comment by jtidal** [comment]
I like the responsive vertical-timeline!

**Comment by sshealy** [comment]
I second the responsive vertical timeline.

**Comment by starsplatter** [comment]
Very nice!

**Comment by phette23** [comment]
:+1:  to the vertical timeline as well

**Comment by queryluke** [comment]
Gah! I'll get the image references fixed tonight and finish stubbing out all the schedule pages in the issue#3.1 branch

**Comment by queryluke** [comment]
I've finished the placeholder for the schedule until we actually get conference events to add. I'll take any critiques and update anything you all would like to see changed.
