### ISSUE TITLE
2017 site

### ISSUE THREAD

**Issue by joshuago78** [code4lib/2016.code4lib.org#391]
I am wondering how to go about reusing this repo for the 2017 conference. I believe Github pages will only work for one site per project, so if we want to keep the 2016 site running, then I believe what I should do is clone this repo and set the remote origin to a new repo at https://github.com/code4lib/2017.code4lib.org.git
- Is this correct?
  - If so, can someone add me as a member of code4lib on Github?
  - If not, please fill me in on a better strategy

**Comment by bibliotechy** [comment]
@joshuago78 I've just sent you an invite to the code4lib organization.

A new repo based on this repo does seem like a reasonable strategy.

**Comment by joshuago78** [comment]
Thank you @bibliotechy

**Comment by queryluke** [comment]
@joshuago78 if need a rundown or have any questions about the code, let me know. There are some additional scripts that I wrote to extract Google Form data into yaml files and jekyll templates. It may be a bit stale, but I can update as necessary.

**Comment by joshuago78** [comment]
@queryluke an overview would be most appreciated. Perhaps we can have a phone call next week. I'm still in the process of putting together a website working group. If you or anyone else on last year's team would like to join in, please let me know.

**Comment by queryluke** [comment]
@joshuago78 I'm on vacation next week, but I'd be happy to re-enlist in the website working group.

**Comment by phette23** [comment]
I'd be willing to help out as well.

**Comment by sdellis** [comment]
Just returning from vacation today, so sorry for the delayed response... I'd be happy to help as well.

**Comment by sdellis** [comment]
FYI - the newly released [Jekyll Admin](https://jekyll.github.io/jekyll-admin/) plugin could come in handy... tested it out locally and it looks cool.  One issue we had last year was that people couldn't update their own content without making pull requests.  This might simplify things, but not sure how it would work with ghpages hosting.

**Comment by queryluke** [comment]
@joshuago78 I saw people are signing up for the [Website Working Group on the wiki](http://wiki.code4lib.org/2017_Conference_Committees). Do you want us to sign up there?

**Comment by joshuago78** [comment]
Yes that would be great. Then I will call a meeting for us to outline some tasks.
