### ISSUE TITLE
Add Attend Page

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#4]
Here are [content ideas](http://wiki.code4lib.org/Conference_Site_Pages#Attend)!

**Comment by starsplatter** [comment]
I'll take this but can't assign it myself.

**Comment by starsplatter** [comment]
I still have this hanging out here, I've been busy. Is this page still needed?

**Comment by queryluke** [comment]
@starsplatter I think so. But it can be short and sweet. Registration won't open until january ([see the LPC's docs](https://trello.com/b/rTeC8Bgx/master-planning-schedule)). So I'm thinking the page just needs to say something along the lines of "Registration and hotel info coming later this year..."
