### ISSUE TITLE
Stub/Mock Speaker Pages

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#5]
Here are [content ideas](http://wiki.code4lib.org/Conference_Site_Pages#Speakers)!

**Comment by jtidal** [comment]
Added a speakers page. Going to add more content later this week.

**Comment by jtidal** [comment]
I tried adding modals for the speaker bio and presentations. However, the modal goes "dark" along with the background when clicked. I think I narrowed it down to the modified bootstrap .css file, but I'm unsure of which class is causing the problem. Could anyone else take a look?
