### ISSUE TITLE
Mobile display cleanup

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#69]
Go through all pages and clean up oddities with mobile display.

**Comment by bibliotechy** [comment]
I was just about to create new issues for a few specific mobile issues, but then saw this one. Should I mention them here in comments?

**Comment by sdellis** [comment]
Please do, @bibliotechy!  I know that @roastduckalamode was planning on working on the testimonials, but was planning to do an audit too.  Any help you can provide would be welcome!

**Comment by bibliotechy** [comment]
These are both seen on Chrome on Android.

The Logo covers the text on mobile.

![screenshot_2015-09-03-13-21-00](https://cloud.githubusercontent.com/assets/1128631/9666887/b9862232-5246-11e5-9346-dc125effcada.png)

The contact button hanging on the  side covers text on mobile.

![logo](https://cloud.githubusercontent.com/assets/1128631/9666894/beee5ec4-5246-11e5-9aa2-03053ba96333.png)
