### ISSUE TITLE
Generate speaker data file from Google Forms and/or Voting App

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#71]
Talk to @cbeer about how he wants the data for the die-bold-o-tron.

**Comment by cbeer** [comment]
Doesn't matter to me (anything is better than mediawiki..), just make it machine readable. Bonus points if the description is encoded with markdown.

**Comment by sdellis** [comment]
Ok, we were planning on using a Google Form for people to propose talks, so we can definitely make it machine readable.  We may be able to generate markdown through some converter...
