### ISSUE TITLE
Targeted Sponsorship blurbs are hard to read

### ISSUE THREAD

**Issue by bibliotechy** [code4lib/2016.code4lib.org#77]
When the targeted sponsorship section is viewed on a screen wide enough to have three columns, the blurbs of the sponsorship become difficult to read. Also, when I finish one, I sometimes have to scroll back up to read the text of the next one, which feels wonky.
<img width="1280" alt="screen shot 2015-09-02 at 8 26 59 pm" src="https://cloud.githubusercontent.com/assets/1128631/9647968/faeb270e-51b0-11e5-950b-932688a32d8f.png">

I'd propose we have one column, no matter the viewing width. Also, that would allow us to add anchors to make it possible to link directly to each targeted sponsorship, which would be nice.

Thoughts?

**Comment by sdellis** [comment]
Yes, I was planning on revisiting that. I can give it a go, unless you've got a particular vision for it you want to contribute.

**Comment by bibliotechy** [comment]
I'm looking at it right now, so I'll make a PR and we'll see how that goes?

**Comment by sdellis** [comment]
Awesome! Thanks... I'm in the [gitter channel](https://gitter.im/C4L-PHL) if you have any questions about the build process.

**Comment by bibliotechy** [comment]
Closed by https://github.com/code4lib/2016.code4lib.org/issues/78

**Comment by bibliotechy** [comment]
Closed by https://github.com/code4lib/2016.code4lib.org/issues/78
