### ISSUE TITLE
Add Code of Conduct page

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#8]
Here are some [content ideas](http://wiki.code4lib.org/Conference_Site_Pages#Conduct)!

**Comment by starsplatter** [comment]
I'll take this but I don't seem to be able to assign it to myself.

**Comment by sdellis** [comment]
I forgot to add the repo to our team.  You should be able to self-assign issues now!

**Comment by starsplatter** [comment]
Linking to elsewhere.
