### ISSUE TITLE
Add Venue Page

### ISSUE THREAD

**Issue by sdellis** [code4lib/2016.code4lib.org#9]
Here are some [content ideas](http://wiki.code4lib.org/Conference_Site_Pages#Venue)!

**Comment by cdmo** [comment]
I just saw this after writing the email out to the Google Group.  Is that link for content ideas all the content we have?

**Comment by sdellis** [comment]
Yes, except that it's almost certain that we will be getting the [Sheraton Society Hill](http://www.sheratonphiladelphiasocietyhill.com/) for March 7-10.  If you have ideas I would say run with them, or bounce them off the group!  I will see what else I can gather for you at the LPC meeting today.

**Comment by cdmo** [comment]
see 1f22b3b521f00ab
